version: "3.9"
services:
  app:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    volumes:
      - .:/app:cached
    command: sleep infinity
    user: root
    ports:
      - "30000:3000"